# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JdAlwi9nEReBnTFJtAq4FX0Co-JB3FeT

**Importing Start Up Data**
"""

import pandas as pd

url = "https://raw.githubusercontent.com/hkuangedu/PythonProgramming/main/Project1_LLM_ESG_Classification.csv"

df_firms = pd.read_csv(url,header=None)

print(df_firms.shape)
display(df_firms.head(3))

# list models that support text generation
from google import genai
from google.colab import userdata

# 1) Load the key and create a client
client = genai.Client(api_key=userdata.get("HF")) #you need to replace the name with your secret name here

# 2) Pick the model and setup parameters
MODEL = "gemini-2.5-flash"

print("--- LLM is activated ---")

"""**Prompt For LLM to Execute (Edit this to configure Accuracy)**"""

system_prompt = """You are a strict ESG classification analyst. Your task is to determine whether a startup's core business is directly related to Environmental, Social, or Governance (ESG) themes.

Classification criteria:
- Environmental: The firm's core product or service directly reduces pollution, conserves resources, generates clean energy, improves energy efficiency, provides sustainable alternatives to harmful products, or protects ecosystems.
- Social: The firm's core product or service directly expands access to essential services for underserved populations, reduces systemic inequality, or addresses poverty, housing, or education gaps.
- Governance: The firm's core product or service directly enables corporate transparency, anti-corruption, ethical compliance, or accountability.

Rules:
- Classify as ESG (1) if the firm's core product or service delivers a direct environmental, social, or governance benefit — even if the firm does not use explicit ESG language.
- A plant-based food company, an eco-friendly service, a clean energy product, a water/waste infrastructure firm, or an energy efficiency firm DOES count as ESG.
- A firm that simply uses technology for general business improvement (e.g., generic SaaS, analytics, marketplaces) does NOT count as ESG, even if it mentions positive impact.
- Charitable giving platforms, general health/wellness products, civic engagement tools, workplace safety software, and medical devices are NOT ESG unless they specifically target underserved or disadvantaged populations.
- A large corporation with broad sustainability initiatives is NOT ESG — only classify startups whose core offering is ESG-related.
- When uncertain, default to 0.

Return ONLY a valid JSON array. Each element must follow this format:
{"firm_id": "the firm_id provided", "label": 0 or 1, "confidence": 0.0 to 1.0, "explanation": "one sentence reason"}"""

import json
import time

results = []
batch_size = 10

for start in range(1, len(df_firms), batch_size):
    batch = df_firms.iloc[start:start + batch_size]

    # Build one user prompt with multiple firms
    user_prompt = "Classify each startup below:\n\n"
    for _, row in batch.iterrows():
        user_prompt += f"firm_id: {row[0]}\nDescription: {row[1]}\n\n"

    response = client.models.generate_content(
        model=MODEL,
        config={"system_instruction": system_prompt},
        contents=user_prompt
    )

    # Parse the JSON array
    try:
        # Strip markdown code fences if the model adds them
        text = response.text.strip()
        if text.startswith("```"):
            text = text.split("\n", 1)[1].rsplit("```", 1)[0]
        batch_results = json.loads(text)
        results.extend(batch_results)
    except:
        # If parsing fails, mark all firms in this batch as errors
        for _, row in batch.iterrows():
            results.append({"firm_id": row[0], "label": None, "confidence": None, "explanation": "PARSE ERROR"})

    time.sleep(1)

print(f"Done! Processed {len(results)} firms.")
df_results = pd.DataFrame(results)
display(df_results.head())

"""**Results from LLM Analysis**"""

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Get the ground truth labels from the original dataframe (skip header row)
df_firms.columns = ["firm_id", "bus_description", "esg_dummy"]
df_truth = df_firms.iloc[1:].copy()
df_truth["esg_dummy"] = df_truth["esg_dummy"].astype(int)

# Merge predictions with ground truth
df_eval = df_truth.merge(df_results, on="firm_id", how="inner")

# Drop any rows where the model failed to return a label
df_eval = df_eval.dropna(subset=["label"])
df_eval["label"] = df_eval["label"].astype(int)

# Calculate metrics
accuracy = accuracy_score(df_eval["esg_dummy"], df_eval["label"])
precision = precision_score(df_eval["esg_dummy"], df_eval["label"])
recall = recall_score(df_eval["esg_dummy"], df_eval["label"])
f1 = f1_score(df_eval["esg_dummy"], df_eval["label"])

print(f"Accuracy:  {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall:    {recall:.4f}")
print(f"F1 Score:  {f1:.4f}")

# Confusion matrix
tn, fp, fn, tp = confusion_matrix(df_eval["esg_dummy"], df_eval["label"]).ravel()
print(f"\nConfusion Matrix:")
print(f"  True Positives:  {tp}")
print(f"  True Negatives:  {tn}")
print(f"  False Positives: {fp} (model said ESG, but wasn't)")
print(f"  False Negatives: {fn} (model said non-ESG, but was)")

"""**False Negatives**"""

# Show the false negatives — actual ESG firms the model missed
false_negatives = df_eval[(df_eval["label"] == 0) & (df_eval["esg_dummy"] == 1)]
print(f"=== FALSE NEGATIVES ({len(false_negatives)}) ===\n")
for _, row in false_negatives.head(10).iterrows():
    print(f"{row['firm_id']}: {row['explanation']}")
    print(f"  Description: {row['bus_description'][:100]}...")
    print()

"""**False Positives**"""

# Show the false positives — firms the model incorrectly called ESG
false_positives = df_eval[(df_eval["label"] == 1) & (df_eval["esg_dummy"] == 0)]
print(f"=== FALSE POSITIVES ({len(false_positives)}) ===\n")
for _, row in false_positives.head(10).iterrows():
    print(f"{row['firm_id']}: {row['explanation']}")
    print(f"  Description: {row['bus_description'][:100]}...")
    print()